title: Your awesome title
lang: en
description: Write an awesome description for your new site here

remote_theme: rundocs/jekyll-rtd-theme

addons_branch: true
edit: true

copyright:
  revision: true

addons:
  - github
  - i18n
  - plugins
  - analytics

# sort
readme_index:
  with_frontmatter: true

sass:
  style: compressed

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

# optional plugins
plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
